# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:


# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 641c1f246b6a871d6985702346d317def5f09faadde3863f348bc975c44ff672af7d2691136313dd652fceb52c1c663138b81af3f282afad2e9b1240f29a8113

test:
  secret_key_base: 37cd95efe81e96581b44ee46b32425390f5f72bcd1a7bf9b5513f958514784db5565f2f666567189386f9db274e18246df2ec4c4fe649c23bac18e1f832d6802

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
